/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define maxCellReport (8)
#define maxNrofSSBs_1 (63)
#define maxNrofCSI_RS_ResourcesRRM_1 (95)
#define maxNrofServingCells (32)
#define maxNrofServingCells_1 (31)
#define maxNrofIndexesToReport2 (64)
#define maxnoofMeasurementInfo (65535)
#define maxofMessageProtocolTests (15)
#define maxnoofQCI (256)
#define maxnoofQoSFlows (64)
#define maxnoofSliceItems (1024)
#define maxnoofContainerListItems (3)
#define maxCellingNBDU (512)
#define maxofContainers (8)
#define maxPLMN (12)
#define maxnoofUEs (65535)
#define maxnoofPMMeasurements (2147483647)
#define maxnoofRICStyles (63)
#define maxnoofAssociatedRANInfo (4294967295)
#define maxnoofParametersInStructure (4294967295)
#define maxnoofItemsInList (4294967295)
#define maxnoofControlAction (65535)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
