#ifndef NETWORK_INTERFACE_TYPE_E2SM_H
#define NETWORK_INTERFACE_TYPE_E2SM_H


// 6.2.2.10

typedef enum{

  NG_NETWORK_INTERFACE_TYPE, 
  XN_NETWORK_INTERFACE_TYPE, 
  F1_NETWORK_INTERFACE_TYPE,
  E1_NETWORK_INTERFACE_TYPE, 
  S1_NETWORK_INTERFACE_TYPE, 
  X2_NETWORK_INTERFACE_TYPE, 
  W1_NETWORK_INTERFACE_TYPE,

  END_NETWORK_INTERFACE_TYPE

} network_interface_type_e;

#endif
