/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define maxE1APid (65535)
#define maxF1APid (4)
#define maxEARFCN (65535)
#define maxNRARFCN (3279165)
#define maxnoofNrCellBands (32)
#define min_val_MME_UE_S1AP_ID (0)
#define max_val_MME_UE_S1AP_ID (4294967295)
#define min_val_QCI (0)
#define max_val_QCI (255)
#define min_val_SubscriberProfileIDforRFP (1)
#define max_val_SubscriberProfileIDforRFP (256)
#define min_val_ENB_UE_X2AP_ID (0)
#define max_val_ENB_UE_X2AP_ID (4095)
#define min_val_E_UTRA_ARFCN (0)
#define max_val_E_UTRA_ARFCN (65535)
#define min_val_NGENB_CU_UE_W1AP_ID (0)
#define max_val_NGENB_CU_UE_W1AP_ID (4294967295)
#define min_val_NGENB_DU_ID (0)
#define max_val_NGENB_DU_ID (68719476735)
#define min_val_AMF_UE_NGAP_ID (0)
#define max_val_AMF_UE_NGAP_ID (1099511627775)
#define min_val_NG_RANnodeUEXnAPID (0)
#define max_val_NG_RANnodeUEXnAPID (4294967295)
#define min_val_GNB_CU_CP_UE_E1AP_ID (0)
#define max_val_GNB_CU_CP_UE_E1AP_ID (4294967295)
#define min_val_GNB_CU_UP_ID (0)
#define max_val_GNB_CU_UP_ID (68719476735)
#define min_val_GNB_CU_UE_F1AP_ID (0)
#define max_val_GNB_CU_UE_F1AP_ID (4294967295)
#define min_val_GNB_DU_ID (0)
#define max_val_GNB_DU_ID (68719476735)
#define min_val_NR_PCI (0)
#define max_val_NR_PCI (1007)
#define maxnoofMessages (65535)
#define maxnoofE2InfoChanges (65535)
#define maxnoofUEInfoChanges (65535)
#define maxnoofRRCstate (8)
#define maxnoofParametersToReport (65535)
#define maxnoofPolicyConditions (65535)
#define maxnoofAssociatedRANParameters (65535)
#define maxnoofUEID (65535)
#define maxnoofCellID (65535)
#define maxnoofRANOutcomeParameters (255)
#define maxnoofParametersinStructure (65535)
#define maxnoofItemsinList (65535)
#define maxnoofUEInfo (65535)
#define maxnoofCellInfo (65535)
#define maxnoofUEeventInfo (65535)
#define maxnoofRANparamTest (255)
#define maxnoofNeighbourCell (65535)
#define maxnoofRICStyles (63)
#define maxnoofCallProcessTypes (65535)
#define maxnoofCallProcessBreakpoints (65535)
#define maxnoofInsertIndication (65535)
#define maxnoofControlAction (65535)
#define maxnoofPolicyAction (65535)
#define maxnoofInsertIndicationActions (63)
#define maxnoofMulCtrlActions (63)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
