/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "e2sm_rc_v1_03_modified.asn"
 * 	`asn1c -gen-APER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_TriggerType_Choice_RRCstate_Item_H_
#define	_TriggerType_Choice_RRCstate_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRC-State.h"
#include "LogicalOR.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TriggerType-Choice-RRCstate-Item */
typedef struct TriggerType_Choice_RRCstate_Item {
	RRC_State_t	 stateChangedTo;
	LogicalOR_t	*logicalOR;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TriggerType_Choice_RRCstate_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TriggerType_Choice_RRCstate_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_TriggerType_Choice_RRCstate_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_TriggerType_Choice_RRCstate_Item_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TriggerType_Choice_RRCstate_Item_H_ */
#include <asn_internal.h>
